image:
  repository: sj26/mailcatcher
  tag: 0.9.0

service:
  httpPort: 80
  smtpPort: 25

ingress:
  enabled: true
  hostname: mailcatcher.example.com
  basicAuth:
    enabled: true
    username: admin
    password: password123
