apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailcatcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mailcatcher.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mailcatcher.name" . }}
    spec:
      containers:
        - name: mailcatcher
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.httpPort }}
            - containerPort: {{ .Values.service.smtpPort }}
