apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ printf "%s:%s" .Values.ingress.basicAuth.username .Values.ingress.basicAuth.password | b64enc }}
