apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 1080
      name: http
    - port: {{ .Values.service.smtpPort }}
      targetPort: 1025
      name: smtp
